---
- name: Install tomcat
  become: yes
  hosts: all
  vars:
    - username: "tomcat"
    - java_home: "/usr/lib/jvm/java-11-openjdk-amd64"
    - home_dir: "/opt/tomcat"
    - tomcat_latest: "/opt/tomcat/latest"
    - default_shell: "/bin/false"
    - tomcat_version: "10.1.14"
    - tomcat_service_file_path: "/etc/systemd/system/tomcat.service"
    - tomcat-users-xml: "conf/tomcat-users.xml"
    - tc_admin_user: "devops"
    - tc_admin_password: "devops"
    - allow-manager-context-xml: '.*'
    - tc-context-locations:
      - /opt/tomcat/latest/webapps/manager/META-INF/context.xml
      - /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
    - deploy_file_name: "jenkins.war"
    - deploy_url: "https://get.jenkins.io/war-stable/2.414.3/jenkins.war"
  tasks:
    - name: update packages
      apt:
        update_cache: yes
    - name: Install java11
      package:
        name: "{{ java_package }}"
        state: present
    - name: add a user tomcat
      ansible.builtin.user:
        name: "{{ username }}"
        create_home: yes
        home: "{{ home_dir }}"
        shell: "{{ default_shell }}"
    - name: Download tomcat
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
        dest: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
    - name: Extract tomcat
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        owner: "{{ username }}"
        group: "{{ username }}"
        dest: "{{ home_dir }}"
        creates: "{{ home_dir }}/apache-tomcat-{{ tomcat_version }}"
        remote_src: yes
    - name: Create a symlink
      ansible.builtin.file:
        src: "{{ home_dir }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ tomcat_latest }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        state: link
    - name: change ownership
      ansible.builtin.file:
        path: "{{ home_dir }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        state: directory
        recurse: yes
    - name: finding shell files
      ansible.builtin.find:
        paths: "{{ tomcat_latest }}/bin"
        patterns: "*.sh"
      register: shell_files_executables
    - name: Printing the previous variable    
      debug:
        var: shell_files_executables
    - name: execuatble permissions to shell files
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0755"
      loop: "{{ shell_files_executables.files }}"
    - name: copy the service file
      ansible.builtin.template:
        src: 'tomcat.service.j2'
        dest: "{{ tomcat_service_file_path }}"
        owner: "{{ username }}"
        group: "{{ username }}"
      notify:
        - Reload the daemon enable and start the tomcat service
    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers
    - name: ensure tomcat service is running
      ansible.builtin.systemd:
        name: 'tomcat.service'
        state: started
    - name: copy the tomcat-users file
      ansible.builtin.template:
        src: 'tomcat-users.xml.j2'
        dest: "{{ tomcat_latest }}/{{ tomcat-users-xml}}"
        owner: "{{ username }}"
        group: "{{ username }}"
      notify:
        - Reload the daemon enable and start the tomcat service
    - name: copy the manager app file
      ansible.builtin.template:
        src: 'manager-context.xml.j2'
        dest: "{{ item }}"
        owner: "{{ username }}"
        group: "{{ username }}"
      loop: "{{ tc-context-locations }}"
      notify:
        - Reload the daemon enable and start the tomcat service
    - name: Deploy any war file
      ansible.builtin.get_url:
        url: "{{ deploy_url }}"
        dest: "{{ tomcat_latest}}/webapps/{{ deploy_file_name }}"
        owner: "{{ username }}"
        group: "{{ username }}"
      notify:
        - Reload the daemon enable and start the tomcat service  
  handlers:  
    - name: Reload the daemon enable and start the tomcat service
      ansible.builtin.systemd:
        name: 'tomcat.service'
        daemon_reload: yes
        enabled: yes
        state: restarted
