---
# writing tasks directly
- name: Install utils
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - python3-pip
    - tree
- name: ensure file is created
  file:
    path: /tmp/msg
    state: directory