---
- name: Install LAMP Stack
  become: yes
  hosts: all
  tasks:
    - name: update packages
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Ubuntu"
    - name: Install apache
      ansible.builtin.package:
        name: "{{ apache_package }}"
        state: present
      notify:
        - ensure apache is enabled and restarted        
    - name: Install php packages
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ php_packages }}"
      notify: 
        - ensure apache is enabled and restarted
    - name: copy the php info page
      ansible.builtin.copy:
        src: 'info.php'
        dest: /var/www/html
      notify: 
        - ensure apache is enabled and restarted        
  handlers:
    - name: ensure apache is enabled and restarted
      ansible.builtin.service:
        name: 'apache2'
        daemon_reload: yes
        enabled: yes
        state: restarted