---
- name: Command Execution from Ansible
  gather_facts: no
  hosts: all
  tasks:
    - name: Execute commands if a specific module not found in ansible
      become: yes
      ansible.builtin.command:
        cmd: 'sh ./ping.sh'
      register: standard_output
    - name: Print the output
      debug:
        msg: "{{ standard_output }}"
    - name: Using ansible magic/special variables
      debug:
        msg: "The clientip is {{ ansible_host }}"