---
- name: Install LAMP
  become: yes
  hosts: webserver
  tasks:
    - name: update packages
      apt:
        update_cache: yes
    - name: Install apache and php
      package:
        - apache2
        - php
        - libapache2-mod-php
    - name: copy info.php
      ansible.builtin.copy:
        src: 'info.php'
        dest: /var/www/html
    - name: Restart apache
      ansible.builtin.systemd:
        name: 'apache2'
        daemon_reload: yes
        enabled: yes
        state: restarted    